### ISSUE TITLE
Discuss?

### ISSUE THREAD

**Issue by laixintao** [ltoddy/jrpc#1]
Hi I am very interesting about the idea that using json as rpc protocol. I think the purpose may be, that it's available for any language without sdk or libs? And also don't need schema migration for this.

But how about bjson or msgpack? Some references here: https://github.com/Vonng/ddia/blob/master/ch4.md#%E4%BA%8C%E8%BF%9B%E5%88%B6%E7%BC%96%E7%A0%81

**Comment by ltoddy** [comment]
Why I create this project is that I want to implement the raft algorithms。
For the present， I need to make a prototype.
In the future, perhaps more will be considered.

**Comment by laixintao** [comment]
OK I see, good luck!
